package com.ower.dsyz.gateway.auto.model;

import java.io.Serializable;
import java.util.Date;

public class GatewayAuthUrl implements Serializable {
    /**
     * 
     * 表 : t_gateway_auth_url
     * 对应字段 : id
     */
    private String id;

    /**
     * 匹配url
     * 表 : t_gateway_auth_url
     * 对应字段 : url_pattern
     */
    private String urlPattern;

    /**
     * 执行类id
     * 表 : t_gateway_auth_url
     * 对应字段 : type_id
     */
    private String typeId;

    /**
     * 备注说明
     * 表 : t_gateway_auth_url
     * 对应字段 : remark
     */
    private String remark;

    /**
     * 
     * 表 : t_gateway_auth_url
     * 对应字段 : create_date
     */
    private Date createDate;

    /**
     * 
     * 表 : t_gateway_auth_url
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 
     * 表 : t_gateway_auth_url
     * 对应字段 : update_date
     */
    private Date updateDate;

    /**
     * 
     * 表 : t_gateway_auth_url
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_gateway_auth_url
     *
     * @mbggenerated Tue Aug 14 15:17:09 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_gateway_auth_url.id：
     */
    public String getId() {
        return id;
    }

    /**
     * set method 
     *
     * @param id  
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * get method 
     *
     * @return t_gateway_auth_url.url_pattern：匹配url
     */
    public String getUrlPattern() {
        return urlPattern;
    }

    /**
     * set method 
     *
     * @param urlPattern  匹配url
     */
    public void setUrlPattern(String urlPattern) {
        this.urlPattern = urlPattern == null ? null : urlPattern.trim();
    }

    /**
     * get method 
     *
     * @return t_gateway_auth_url.type_id：执行类id
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * set method 
     *
     * @param typeId  执行类id
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * get method 
     *
     * @return t_gateway_auth_url.remark：备注说明
     */
    public String getRemark() {
        return remark;
    }

    /**
     * set method 
     *
     * @param remark  备注说明
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * get method 
     *
     * @return t_gateway_auth_url.create_date：
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * set method 
     *
     * @param createDate  
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * get method 
     *
     * @return t_gateway_auth_url.create_user：
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_gateway_auth_url.update_date：
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * set method 
     *
     * @param updateDate  
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * get method 
     *
     * @return t_gateway_auth_url.update_user：
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", urlPattern=").append(urlPattern);
        sb.append(", typeId=").append(typeId);
        sb.append(", remark=").append(remark);
        sb.append(", createDate=").append(createDate);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateUser=").append(updateUser);
        sb.append("]");
        return sb.toString();
    }

}