package com.ower.dsyz.gateway.auto.model;

import java.io.Serializable;
import java.util.Date;

public class GatewayExcuteType implements Serializable {
    /**
     * 
     * 表 : t_gateway_excute_type
     * 对应字段 : id
     */
    private String id;

    /**
     * 
     * 表 : t_gateway_excute_type
     * 对应字段 : name
     */
    private String name;

    /**
     * 类全名
     * 表 : t_gateway_excute_type
     * 对应字段 : class_name
     */
    private String className;

    /**
     * 备注
     * 表 : t_gateway_excute_type
     * 对应字段 : remark
     */
    private String remark;

    /**
     * 
     * 表 : t_gateway_excute_type
     * 对应字段 : create_date
     */
    private Date createDate;

    /**
     * 
     * 表 : t_gateway_excute_type
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 
     * 表 : t_gateway_excute_type
     * 对应字段 : update_date
     */
    private Date updateDate;

    /**
     * 
     * 表 : t_gateway_excute_type
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_gateway_excute_type
     *
     * @mbggenerated Mon Dec 03 14:46:38 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_gateway_excute_type.id：
     */
    public String getId() {
        return id;
    }

    /**
     * set method 
     *
     * @param id  
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * get method 
     *
     * @return t_gateway_excute_type.name：
     */
    public String getName() {
        return name;
    }

    /**
     * set method 
     *
     * @param name  
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * get method 
     *
     * @return t_gateway_excute_type.class_name：类全名
     */
    public String getClassName() {
        return className;
    }

    /**
     * set method 
     *
     * @param className  类全名
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * get method 
     *
     * @return t_gateway_excute_type.remark：备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * set method 
     *
     * @param remark  备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * get method 
     *
     * @return t_gateway_excute_type.create_date：
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * set method 
     *
     * @param createDate  
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * get method 
     *
     * @return t_gateway_excute_type.create_user：
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_gateway_excute_type.update_date：
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * set method 
     *
     * @param updateDate  
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * get method 
     *
     * @return t_gateway_excute_type.update_user：
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", className=").append(className);
        sb.append(", remark=").append(remark);
        sb.append(", createDate=").append(createDate);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateUser=").append(updateUser);
        sb.append("]");
        return sb.toString();
    }
}