package com.ower.dsyz.wechat.auto.model;

import java.io.Serializable;
import java.util.Date;

public class WechatApp implements Serializable {
    /**
     * id
     * 表 : t_wechat_app
     * 对应字段 : id
     */
    private String id;

    /**
     * 公众号名称
     * 表 : t_wechat_app
     * 对应字段 : app_name
     */
    private String appName;

    /**
     * appId
     * 表 : t_wechat_app
     * 对应字段 : app_id
     */
    private String appId;

    /**
     * 秘钥
     * 表 : t_wechat_app
     * 对应字段 : secret
     */
    private String secret;

    /**
     * token
     * 表 : t_wechat_app
     * 对应字段 : token
     */
    private String token;

    /**
     * 安全域名
     * 表 : t_wechat_app
     * 对应字段 : domain
     */
    private String domain;

    /**
     * 微信号（原始id）
     * 表 : t_wechat_app
     * 对应字段 : code
     */
    private String code;

    /**
     * 消息加密盐
     * 表 : t_wechat_app
     * 对应字段 : mess_secret
     */
    private String messSecret;

    /**
     * 是否有效
     * 表 : t_wechat_app
     * 对应字段 : is_valid
     */
    private String isValid;

    /**
     * 备注
     * 表 : t_wechat_app
     * 对应字段 : remark
     */
    private String remark;

    /**
     * 创建时间
     * 表 : t_wechat_app
     * 对应字段 : create_date
     */
    private Date createDate;

    /**
     * 修改时间
     * 表 : t_wechat_app
     * 对应字段 : update_date
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_wechat_app
     *
     * @mbggenerated Tue Jan 16 17:23:56 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_wechat_app.id：id
     */
    public String getId() {
        return id;
    }

    /**
     * set method 
     *
     * @param id  id
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_app.app_name：公众号名称
     */
    public String getAppName() {
        return appName;
    }

    /**
     * set method 
     *
     * @param appName  公众号名称
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_app.app_id：appId
     */
    public String getAppId() {
        return appId;
    }

    /**
     * set method 
     *
     * @param appId  appId
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_app.secret：秘钥
     */
    public String getSecret() {
        return secret;
    }

    /**
     * set method 
     *
     * @param secret  秘钥
     */
    public void setSecret(String secret) {
        this.secret = secret == null ? null : secret.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_app.token：token
     */
    public String getToken() {
        return token;
    }

    /**
     * set method 
     *
     * @param token  token
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_app.domain：安全域名
     */
    public String getDomain() {
        return domain;
    }

    /**
     * set method 
     *
     * @param domain  安全域名
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_app.code：微信号（原始id）
     */
    public String getCode() {
        return code;
    }

    /**
     * set method 
     *
     * @param code  微信号（原始id）
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_app.mess_secret：消息加密盐
     */
    public String getMessSecret() {
        return messSecret;
    }

    /**
     * set method 
     *
     * @param messSecret  消息加密盐
     */
    public void setMessSecret(String messSecret) {
        this.messSecret = messSecret == null ? null : messSecret.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_app.is_valid：是否有效
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * set method 
     *
     * @param isValid  是否有效
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_app.remark：备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * set method 
     *
     * @param remark  备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_app.create_date：创建时间
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * set method 
     *
     * @param createDate  创建时间
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * get method 
     *
     * @return t_wechat_app.update_date：修改时间
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * set method 
     *
     * @param updateDate  修改时间
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appName=").append(appName);
        sb.append(", appId=").append(appId);
        sb.append(", secret=").append(secret);
        sb.append(", token=").append(token);
        sb.append(", domain=").append(domain);
        sb.append(", code=").append(code);
        sb.append(", messSecret=").append(messSecret);
        sb.append(", isValid=").append(isValid);
        sb.append(", remark=").append(remark);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append("]");
        return sb.toString();
    }
}