package com.ower.dsyz.wechat.auto.model;

import java.io.Serializable;
import java.util.Date;

public class WechatMessage implements Serializable {
    /**
     * id
     * 表 : t_wechat_message
     * 对应字段 : id
     */
    private String id;

    /**
     * appId
     * 表 : t_wechat_message
     * 对应字段 : app_id
     */
    private String appId;

    /**
     * 触发事件
     * 表 : t_wechat_message
     * 对应字段 : event_type
     */
    private String eventType;

    /**
     * 消息类型
     * 表 : t_wechat_message
     * 对应字段 : mess_type
     */
    private String messType;

    /**
     * 消息标题
     * 表 : t_wechat_message
     * 对应字段 : title
     */
    private String title;

    /**
     * 消息url
     * 表 : t_wechat_message
     * 对应字段 : url
     */
    private String url;

    /**
     * 消息图片地址
     * 表 : t_wechat_message
     * 对应字段 : img_url
     */
    private String imgUrl;

    /**
     * 消息内容描述
     * 表 : t_wechat_message
     * 对应字段 : description
     */
    private String description;

    /**
     * 排序
     * 表 : t_wechat_message
     * 对应字段 : mess_order
     */
    private Integer messOrder;

    /**
     * 父级消息id
     * 表 : t_wechat_message
     * 对应字段 : parent_id
     */
    private String parentId;

    /**
     * 备注
     * 表 : t_wechat_message
     * 对应字段 : remark
     */
    private String remark;

    /**
     * 是否有效
     * 表 : t_wechat_message
     * 对应字段 : is_valid
     */
    private String isValid;

    /**
     * 创建时间
     * 表 : t_wechat_message
     * 对应字段 : create_date
     */
    private Date createDate;

    /**
     * 修改时间
     * 表 : t_wechat_message
     * 对应字段 : update_date
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_wechat_message
     *
     * @mbggenerated Fri Jan 19 17:22:40 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_wechat_message.id：id
     */
    public String getId() {
        return id;
    }

    /**
     * set method 
     *
     * @param id  id
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_message.app_id：appId
     */
    public String getAppId() {
        return appId;
    }

    /**
     * set method 
     *
     * @param appId  appId
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_message.event_type：触发事件
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * set method 
     *
     * @param eventType  触发事件
     */
    public void setEventType(String eventType) {
        this.eventType = eventType == null ? null : eventType.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_message.mess_type：消息类型
     */
    public String getMessType() {
        return messType;
    }

    /**
     * set method 
     *
     * @param messType  消息类型
     */
    public void setMessType(String messType) {
        this.messType = messType == null ? null : messType.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_message.title：消息标题
     */
    public String getTitle() {
        return title;
    }

    /**
     * set method 
     *
     * @param title  消息标题
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_message.url：消息url
     */
    public String getUrl() {
        return url;
    }

    /**
     * set method 
     *
     * @param url  消息url
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_message.img_url：消息图片地址
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * set method 
     *
     * @param imgUrl  消息图片地址
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_message.description：消息内容描述
     */
    public String getDescription() {
        return description;
    }

    /**
     * set method 
     *
     * @param description  消息内容描述
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_message.mess_order：排序
     */
    public Integer getMessOrder() {
        return messOrder;
    }

    /**
     * set method 
     *
     * @param messOrder  排序
     */
    public void setMessOrder(Integer messOrder) {
        this.messOrder = messOrder;
    }

    /**
     * get method 
     *
     * @return t_wechat_message.parent_id：父级消息id
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * set method 
     *
     * @param parentId  父级消息id
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_message.remark：备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * set method 
     *
     * @param remark  备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_message.is_valid：是否有效
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * set method 
     *
     * @param isValid  是否有效
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * get method 
     *
     * @return t_wechat_message.create_date：创建时间
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * set method 
     *
     * @param createDate  创建时间
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * get method 
     *
     * @return t_wechat_message.update_date：修改时间
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * set method 
     *
     * @param updateDate  修改时间
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appId=").append(appId);
        sb.append(", eventType=").append(eventType);
        sb.append(", messType=").append(messType);
        sb.append(", title=").append(title);
        sb.append(", url=").append(url);
        sb.append(", imgUrl=").append(imgUrl);
        sb.append(", description=").append(description);
        sb.append(", messOrder=").append(messOrder);
        sb.append(", parentId=").append(parentId);
        sb.append(", remark=").append(remark);
        sb.append(", isValid=").append(isValid);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append("]");
        return sb.toString();
    }
}