package com.ower.dsyz.admin.auto.model;

import java.io.Serializable;
import java.util.Date;

public class AdminUserLogin implements Serializable {
    /**
     * 用户id
     * 表 : t_admin_user_login
     * 对应字段 : user_id
     */
    private String userId;

    /**
     * 登录账号
     * 表 : t_admin_user_login
     * 对应字段 : login_name
     */
    private String loginName;

    /**
     * 手机号
     * 表 : t_admin_user_login
     * 对应字段 : phone
     */
    private String phone;

    /**
     * 密码
     * 表 : t_admin_user_login
     * 对应字段 : password
     */
    private String password;

    /**
     * 密码盐
     * 表 : t_admin_user_login
     * 对应字段 : salt
     */
    private String salt;

    /**
     * 备注
     * 表 : t_admin_user_login
     * 对应字段 : remark
     */
    private String remark;

    /**
     * 创建人
     * 表 : t_admin_user_login
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 创建时间
     * 表 : t_admin_user_login
     * 对应字段 : create_date
     */
    private Date createDate;

    /**
     * 修改人
     * 表 : t_admin_user_login
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * 修改时间
     * 表 : t_admin_user_login
     * 对应字段 : update_date
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_admin_user_login
     *
     * @mbggenerated Thu Jul 26 10:23:27 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_admin_user_login.user_id：用户id
     */
    public String getUserId() {
        return userId;
    }

    /**
     * set method 
     *
     * @param userId  用户id
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_user_login.login_name：登录账号
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * set method 
     *
     * @param loginName  登录账号
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_user_login.phone：手机号
     */
    public String getPhone() {
        return phone;
    }

    /**
     * set method 
     *
     * @param phone  手机号
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_user_login.password：密码
     */
    public String getPassword() {
        return password;
    }

    /**
     * set method 
     *
     * @param password  密码
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_user_login.salt：密码盐
     */
    public String getSalt() {
        return salt;
    }

    /**
     * set method 
     *
     * @param salt  密码盐
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_user_login.remark：备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * set method 
     *
     * @param remark  备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_user_login.create_user：创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_user_login.create_date：创建时间
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * set method 
     *
     * @param createDate  创建时间
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * get method 
     *
     * @return t_admin_user_login.update_user：修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_user_login.update_date：修改时间
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * set method 
     *
     * @param updateDate  修改时间
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", loginName=").append(loginName);
        sb.append(", phone=").append(phone);
        sb.append(", password=").append(password);
        sb.append(", salt=").append(salt);
        sb.append(", remark=").append(remark);
        sb.append(", createUser=").append(createUser);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append("]");
        return sb.toString();
    }
}