package com.ower.dsyz.admin.auto.model;

import java.io.Serializable;
import java.util.Date;

public class AdminUserRole implements Serializable {
    /**
     * 
     * 表 : t_admin_user_role
     * 对应字段 : id
     */
    private String id;

    /**
     * 用户id
     * 表 : t_admin_user_role
     * 对应字段 : user_id
     */
    private String userId;

    /**
     * 
     * 表 : t_admin_user_role
     * 对应字段 : role_id
     */
    private String roleId;

    /**
     * 描述
     * 表 : t_admin_user_role
     * 对应字段 : remake
     */
    private String remake;

    /**
     * 创建人
     * 表 : t_admin_user_role
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 创建日期
     * 表 : t_admin_user_role
     * 对应字段 : create_date
     */
    private Date createDate;

    /**
     * 修改人
     * 表 : t_admin_user_role
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * 修改日期
     * 表 : t_admin_user_role
     * 对应字段 : update_date
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_admin_user_role
     *
     * @mbggenerated Thu Jul 26 17:41:32 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_admin_user_role.id：
     */
    public String getId() {
        return id;
    }

    /**
     * set method 
     *
     * @param id  
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_user_role.user_id：用户id
     */
    public String getUserId() {
        return userId;
    }

    /**
     * set method 
     *
     * @param userId  用户id
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_user_role.role_id：
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * set method 
     *
     * @param roleId  
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_user_role.remake：描述
     */
    public String getRemake() {
        return remake;
    }

    /**
     * set method 
     *
     * @param remake  描述
     */
    public void setRemake(String remake) {
        this.remake = remake == null ? null : remake.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_user_role.create_user：创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_user_role.create_date：创建日期
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * set method 
     *
     * @param createDate  创建日期
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * get method 
     *
     * @return t_admin_user_role.update_user：修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_user_role.update_date：修改日期
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * set method 
     *
     * @param updateDate  修改日期
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", roleId=").append(roleId);
        sb.append(", remake=").append(remake);
        sb.append(", createUser=").append(createUser);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append("]");
        return sb.toString();
    }
}