package com.ower.dsyz.admin.auto.model;

import java.io.Serializable;
import java.util.Date;

public class AdminInstitution implements Serializable {
    /**
     * 机构id
     * 表 : t_admin_institution
     * 对应字段 : ins_id
     */
    private String insId;

    /**
     * 机构的名称（金财互联、服务商、普通客户的名称）
     * 表 : t_admin_institution
     * 对应字段 : ins_name
     */
    private String insName;

    /**
     * 机构简称
     * 表 : t_admin_institution
     * 对应字段 : ins_short_name
     */
    private String insShortName;

    /**
     * 组织机构代码（社会停信用代码）
     * 表 : t_admin_institution
     * 对应字段 : organization_code
     */
    private String organizationCode;

    /**
     * 
     * 表 : t_admin_institution
     * 对应字段 : type_id
     */
    private String typeId;

    /**
     * 
     * 表 : t_admin_institution
     * 对应字段 : bus_type_id
     */
    private String busTypeId;

    /**
     * 行业类型（01计算机软件02计算机硬件）
     * 表 : t_admin_institution
     * 对应字段 : industry_type
     */
    private String industryType;

    /**
     * 企业法人
     * 表 : t_admin_institution
     * 对应字段 : legal
     */
    private String legal;

    /**
     * 联系人
     * 表 : t_admin_institution
     * 对应字段 : contact
     */
    private String contact;

    /**
     * 联系人手机号码
     * 表 : t_admin_institution
     * 对应字段 : phone
     */
    private String phone;

    /**
     * 机构管理员
     * 表 : t_admin_institution
     * 对应字段 : ins_manager
     */
    private String insManager;

    /**
     * 管理员电话
     * 表 : t_admin_institution
     * 对应字段 : ins_manager_phone
     */
    private String insManagerPhone;

    /**
     * 企业地址
     * 表 : t_admin_institution
     * 对应字段 : address
     */
    private String address;

    /**
     * 企业网址
     * 表 : t_admin_institution
     * 对应字段 : addr_web
     */
    private String addrWeb;

    /**
     * 背景图片
     * 表 : t_admin_institution
     * 对应字段 : ins_logo_backgroud
     */
    private String insLogoBackgroud;

    /**
     * 机构logo
     * 表 : t_admin_institution
     * 对应字段 : ins_logo
     */
    private String insLogo;

    /**
     * 描述
     * 表 : t_admin_institution
     * 对应字段 : remark
     */
    private String remark;

    /**
     * 是否启用
     * 表 : t_admin_institution
     * 对应字段 : is_valid
     */
    private String isValid;

    /**
     * 创建人
     * 表 : t_admin_institution
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 创建日期
     * 表 : t_admin_institution
     * 对应字段 : create_date
     */
    private Date createDate;

    /**
     * 修改人
     * 表 : t_admin_institution
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * 修改日期
     * 表 : t_admin_institution
     * 对应字段 : update_date
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_admin_institution
     *
     * @mbggenerated Mon Jun 04 19:51:03 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_admin_institution.ins_id：机构id
     */
    public String getInsId() {
        return insId;
    }

    /**
     * set method 
     *
     * @param insId  机构id
     */
    public void setInsId(String insId) {
        this.insId = insId == null ? null : insId.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.ins_name：机构的名称（金财互联、服务商、普通客户的名称）
     */
    public String getInsName() {
        return insName;
    }

    /**
     * set method 
     *
     * @param insName  机构的名称（金财互联、服务商、普通客户的名称）
     */
    public void setInsName(String insName) {
        this.insName = insName == null ? null : insName.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.ins_short_name：机构简称
     */
    public String getInsShortName() {
        return insShortName;
    }

    /**
     * set method 
     *
     * @param insShortName  机构简称
     */
    public void setInsShortName(String insShortName) {
        this.insShortName = insShortName == null ? null : insShortName.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.organization_code：组织机构代码（社会停信用代码）
     */
    public String getOrganizationCode() {
        return organizationCode;
    }

    /**
     * set method 
     *
     * @param organizationCode  组织机构代码（社会停信用代码）
     */
    public void setOrganizationCode(String organizationCode) {
        this.organizationCode = organizationCode == null ? null : organizationCode.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.type_id：
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * set method 
     *
     * @param typeId  
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.bus_type_id：
     */
    public String getBusTypeId() {
        return busTypeId;
    }

    /**
     * set method 
     *
     * @param busTypeId  
     */
    public void setBusTypeId(String busTypeId) {
        this.busTypeId = busTypeId == null ? null : busTypeId.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.industry_type：行业类型（01计算机软件02计算机硬件）
     */
    public String getIndustryType() {
        return industryType;
    }

    /**
     * set method 
     *
     * @param industryType  行业类型（01计算机软件02计算机硬件）
     */
    public void setIndustryType(String industryType) {
        this.industryType = industryType == null ? null : industryType.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.legal：企业法人
     */
    public String getLegal() {
        return legal;
    }

    /**
     * set method 
     *
     * @param legal  企业法人
     */
    public void setLegal(String legal) {
        this.legal = legal == null ? null : legal.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.contact：联系人
     */
    public String getContact() {
        return contact;
    }

    /**
     * set method 
     *
     * @param contact  联系人
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.phone：联系人手机号码
     */
    public String getPhone() {
        return phone;
    }

    /**
     * set method 
     *
     * @param phone  联系人手机号码
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.ins_manager：机构管理员
     */
    public String getInsManager() {
        return insManager;
    }

    /**
     * set method 
     *
     * @param insManager  机构管理员
     */
    public void setInsManager(String insManager) {
        this.insManager = insManager == null ? null : insManager.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.ins_manager_phone：管理员电话
     */
    public String getInsManagerPhone() {
        return insManagerPhone;
    }

    /**
     * set method 
     *
     * @param insManagerPhone  管理员电话
     */
    public void setInsManagerPhone(String insManagerPhone) {
        this.insManagerPhone = insManagerPhone == null ? null : insManagerPhone.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.address：企业地址
     */
    public String getAddress() {
        return address;
    }

    /**
     * set method 
     *
     * @param address  企业地址
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.addr_web：企业网址
     */
    public String getAddrWeb() {
        return addrWeb;
    }

    /**
     * set method 
     *
     * @param addrWeb  企业网址
     */
    public void setAddrWeb(String addrWeb) {
        this.addrWeb = addrWeb == null ? null : addrWeb.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.ins_logo_backgroud：背景图片
     */
    public String getInsLogoBackgroud() {
        return insLogoBackgroud;
    }

    /**
     * set method 
     *
     * @param insLogoBackgroud  背景图片
     */
    public void setInsLogoBackgroud(String insLogoBackgroud) {
        this.insLogoBackgroud = insLogoBackgroud == null ? null : insLogoBackgroud.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.ins_logo：机构logo
     */
    public String getInsLogo() {
        return insLogo;
    }

    /**
     * set method 
     *
     * @param insLogo  机构logo
     */
    public void setInsLogo(String insLogo) {
        this.insLogo = insLogo == null ? null : insLogo.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.remark：描述
     */
    public String getRemark() {
        return remark;
    }

    /**
     * set method 
     *
     * @param remark  描述
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.is_valid：是否启用
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * set method 
     *
     * @param isValid  是否启用
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.create_user：创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.create_date：创建日期
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * set method 
     *
     * @param createDate  创建日期
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * get method 
     *
     * @return t_admin_institution.update_user：修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_institution.update_date：修改日期
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * set method 
     *
     * @param updateDate  修改日期
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", insId=").append(insId);
        sb.append(", insName=").append(insName);
        sb.append(", insShortName=").append(insShortName);
        sb.append(", organizationCode=").append(organizationCode);
        sb.append(", typeId=").append(typeId);
        sb.append(", busTypeId=").append(busTypeId);
        sb.append(", industryType=").append(industryType);
        sb.append(", legal=").append(legal);
        sb.append(", contact=").append(contact);
        sb.append(", phone=").append(phone);
        sb.append(", insManager=").append(insManager);
        sb.append(", insManagerPhone=").append(insManagerPhone);
        sb.append(", address=").append(address);
        sb.append(", addrWeb=").append(addrWeb);
        sb.append(", insLogoBackgroud=").append(insLogoBackgroud);
        sb.append(", insLogo=").append(insLogo);
        sb.append(", remark=").append(remark);
        sb.append(", isValid=").append(isValid);
        sb.append(", createUser=").append(createUser);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append("]");
        return sb.toString();
    }
}