package com.ower.dsyz.admin.auto.model;

import java.io.Serializable;
import java.util.Date;

public class AdminDepartment implements Serializable {
    /**
     * 
     * 表 : t_admin_department
     * 对应字段 : dep_id
     */
    private String depId;

    /**
     * 
     * 表 : t_admin_department
     * 对应字段 : dep_name
     */
    private String depName;

    /**
     * 
     * 表 : t_admin_department
     * 对应字段 : ins_id
     */
    private String insId;

    /**
     * 根机构的parent_id为000
     * 表 : t_admin_department
     * 对应字段 : parent_dep_Id
     */
    private String parentDepId;

    /**
     * 每层由三位数字构成，每层由001开始计数
     * 表 : t_admin_department
     * 对应字段 : path_code
     */
    private String pathCode;

    /**
     * 部门地址
     * 表 : t_admin_department
     * 对应字段 : address
     */
    private String address;

    /**
     * 联系人
     * 表 : t_admin_department
     * 对应字段 : contactor
     */
    private String contactor;

    /**
     * 所在地区
     * 表 : t_admin_department
     * 对应字段 : area
     */
    private String area;

    /**
     * 
     * 表 : t_admin_department
     * 对应字段 : longitude
     */
    private String longitude;

    /**
     * 
     * 表 : t_admin_department
     * 对应字段 : latitude
     */
    private String latitude;

    /**
     * Y:是，N:否
     * 表 : t_admin_department
     * 对应字段 : Is_valid
     */
    private String isValid;

    /**
     * 描述
     * 表 : t_admin_department
     * 对应字段 : REMARK
     */
    private String remark;

    /**
     * 创建人
     * 表 : t_admin_department
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 创建日期
     * 表 : t_admin_department
     * 对应字段 : create_date
     */
    private Date createDate;

    /**
     * 修改人
     * 表 : t_admin_department
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * 修改日期
     * 表 : t_admin_department
     * 对应字段 : update_date
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_admin_department
     *
     * @mbggenerated Mon Jun 04 19:51:03 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_admin_department.dep_id：
     */
    public String getDepId() {
        return depId;
    }

    /**
     * set method 
     *
     * @param depId  
     */
    public void setDepId(String depId) {
        this.depId = depId == null ? null : depId.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_department.dep_name：
     */
    public String getDepName() {
        return depName;
    }

    /**
     * set method 
     *
     * @param depName  
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_department.ins_id：
     */
    public String getInsId() {
        return insId;
    }

    /**
     * set method 
     *
     * @param insId  
     */
    public void setInsId(String insId) {
        this.insId = insId == null ? null : insId.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_department.parent_dep_Id：根机构的parent_id为000
     */
    public String getParentDepId() {
        return parentDepId;
    }

    /**
     * set method 
     *
     * @param parentDepId  根机构的parent_id为000
     */
    public void setParentDepId(String parentDepId) {
        this.parentDepId = parentDepId == null ? null : parentDepId.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_department.path_code：每层由三位数字构成，每层由001开始计数
     */
    public String getPathCode() {
        return pathCode;
    }

    /**
     * set method 
     *
     * @param pathCode  每层由三位数字构成，每层由001开始计数
     */
    public void setPathCode(String pathCode) {
        this.pathCode = pathCode == null ? null : pathCode.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_department.address：部门地址
     */
    public String getAddress() {
        return address;
    }

    /**
     * set method 
     *
     * @param address  部门地址
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_department.contactor：联系人
     */
    public String getContactor() {
        return contactor;
    }

    /**
     * set method 
     *
     * @param contactor  联系人
     */
    public void setContactor(String contactor) {
        this.contactor = contactor == null ? null : contactor.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_department.area：所在地区
     */
    public String getArea() {
        return area;
    }

    /**
     * set method 
     *
     * @param area  所在地区
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_department.longitude：
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * set method 
     *
     * @param longitude  
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_department.latitude：
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * set method 
     *
     * @param latitude  
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_department.Is_valid：Y:是，N:否
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * set method 
     *
     * @param isValid  Y:是，N:否
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_department.REMARK：描述
     */
    public String getRemark() {
        return remark;
    }

    /**
     * set method 
     *
     * @param remark  描述
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_department.create_user：创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_department.create_date：创建日期
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * set method 
     *
     * @param createDate  创建日期
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * get method 
     *
     * @return t_admin_department.update_user：修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_department.update_date：修改日期
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * set method 
     *
     * @param updateDate  修改日期
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", depId=").append(depId);
        sb.append(", depName=").append(depName);
        sb.append(", insId=").append(insId);
        sb.append(", parentDepId=").append(parentDepId);
        sb.append(", pathCode=").append(pathCode);
        sb.append(", address=").append(address);
        sb.append(", contactor=").append(contactor);
        sb.append(", area=").append(area);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", isValid=").append(isValid);
        sb.append(", remark=").append(remark);
        sb.append(", createUser=").append(createUser);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append("]");
        return sb.toString();
    }
}