package com.ower.dsyz.admin.auto.model;

import java.io.Serializable;
import java.util.Date;

public class AdminDepUser implements Serializable {
    /**
     * 
     * 表 : t_admin_dep_user
     * 对应字段 : dep_user_id
     */
    private String depUserId;

    /**
     * 
     * 表 : t_admin_dep_user
     * 对应字段 : user_id
     */
    private String userId;

    /**
     * 
     * 表 : t_admin_dep_user
     * 对应字段 : dep_id
     */
    private String depId;

    /**
     * 是否有效，取值N/Y，缺省值是Y
     * 表 : t_admin_dep_user
     * 对应字段 : is_valid
     */
    private String isValid;

    /**
     * 描述
     * 表 : t_admin_dep_user
     * 对应字段 : remark
     */
    private String remark;

    /**
     * 创建人
     * 表 : t_admin_dep_user
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 创建日期
     * 表 : t_admin_dep_user
     * 对应字段 : create_date
     */
    private Date createDate;

    /**
     * 修改人
     * 表 : t_admin_dep_user
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * 修改日期
     * 表 : t_admin_dep_user
     * 对应字段 : update_date
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_admin_dep_user
     *
     * @mbggenerated Thu Jul 26 10:38:36 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_admin_dep_user.dep_user_id：
     */
    public String getDepUserId() {
        return depUserId;
    }

    /**
     * set method 
     *
     * @param depUserId  
     */
    public void setDepUserId(String depUserId) {
        this.depUserId = depUserId == null ? null : depUserId.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_dep_user.user_id：
     */
    public String getUserId() {
        return userId;
    }

    /**
     * set method 
     *
     * @param userId  
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_dep_user.dep_id：
     */
    public String getDepId() {
        return depId;
    }

    /**
     * set method 
     *
     * @param depId  
     */
    public void setDepId(String depId) {
        this.depId = depId == null ? null : depId.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_dep_user.is_valid：是否有效，取值N/Y，缺省值是Y
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * set method 
     *
     * @param isValid  是否有效，取值N/Y，缺省值是Y
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_dep_user.remark：描述
     */
    public String getRemark() {
        return remark;
    }

    /**
     * set method 
     *
     * @param remark  描述
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_dep_user.create_user：创建人
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  创建人
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_dep_user.create_date：创建日期
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * set method 
     *
     * @param createDate  创建日期
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * get method 
     *
     * @return t_admin_dep_user.update_user：修改人
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  修改人
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * get method 
     *
     * @return t_admin_dep_user.update_date：修改日期
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * set method 
     *
     * @param updateDate  修改日期
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", depUserId=").append(depUserId);
        sb.append(", userId=").append(userId);
        sb.append(", depId=").append(depId);
        sb.append(", isValid=").append(isValid);
        sb.append(", remark=").append(remark);
        sb.append(", createUser=").append(createUser);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append("]");
        return sb.toString();
    }
}