package com.ower.dsyz.logCenter.auto.model;

import java.io.Serializable;
import java.util.Date;

public class LogAuth implements Serializable {
    /**
     * 
     * 表 : t_log_auth
     * 对应字段 : id
     */
    private String id;

    /**
     * 
     * 表 : t_log_auth
     * 对应字段 : ip
     */
    private String ip;

    /**
     * 
     * 表 : t_log_auth
     * 对应字段 : rsa_public
     */
    private String rsaPublic;

    /**
     * 
     * 表 : t_log_auth
     * 对应字段 : rsa_private
     */
    private String rsaPrivate;

    /**
     * 
     * 表 : t_log_auth
     * 对应字段 : level
     */
    private Integer level;

    /**
     * 
     * 表 : t_log_auth
     * 对应字段 : is_valid
     */
    private String isValid;

    /**
     * 
     * 表 : t_log_auth
     * 对应字段 : create_date
     */
    private Date createDate;

    /**
     * 
     * 表 : t_log_auth
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 
     * 表 : t_log_auth
     * 对应字段 : update_time
     */
    private Date updateTime;

    /**
     * 
     * 表 : t_log_auth
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_log_auth
     *
     * @mbggenerated Fri Sep 21 10:45:00 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_log_auth.id：
     */
    public String getId() {
        return id;
    }

    /**
     * set method 
     *
     * @param id  
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * get method 
     *
     * @return t_log_auth.ip：
     */
    public String getIp() {
        return ip;
    }

    /**
     * set method 
     *
     * @param ip  
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * get method 
     *
     * @return t_log_auth.rsa_public：
     */
    public String getRsaPublic() {
        return rsaPublic;
    }

    /**
     * set method 
     *
     * @param rsaPublic  
     */
    public void setRsaPublic(String rsaPublic) {
        this.rsaPublic = rsaPublic == null ? null : rsaPublic.trim();
    }

    /**
     * get method 
     *
     * @return t_log_auth.rsa_private：
     */
    public String getRsaPrivate() {
        return rsaPrivate;
    }

    /**
     * set method 
     *
     * @param rsaPrivate  
     */
    public void setRsaPrivate(String rsaPrivate) {
        this.rsaPrivate = rsaPrivate == null ? null : rsaPrivate.trim();
    }

    /**
     * get method 
     *
     * @return t_log_auth.level：
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * set method 
     *
     * @param level  
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * get method 
     *
     * @return t_log_auth.is_valid：
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * set method 
     *
     * @param isValid  
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * get method 
     *
     * @return t_log_auth.create_date：
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * set method 
     *
     * @param createDate  
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * get method 
     *
     * @return t_log_auth.create_user：
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_log_auth.update_time：
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * set method 
     *
     * @param updateTime  
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * get method 
     *
     * @return t_log_auth.update_user：
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ip=").append(ip);
        sb.append(", rsaPublic=").append(rsaPublic);
        sb.append(", rsaPrivate=").append(rsaPrivate);
        sb.append(", level=").append(level);
        sb.append(", isValid=").append(isValid);
        sb.append(", createDate=").append(createDate);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append("]");
        return sb.toString();
    }
}