package com.ower.dsyz.logCenter.auto.model;

import java.io.Serializable;
import java.util.Date;

public class LogDetail implements Serializable {
    /**
     * 
     * 表 : t_log_detail
     * 对应字段 : id
     */
    private String id;

    /**
     * 
     * 表 : t_log_detail
     * 对应字段 : ip
     */
    private String ip;

    /**
     * 
     * 表 : t_log_detail
     * 对应字段 : app_name
     */
    private String appName;

    /**
     * 
     * 表 : t_log_detail
     * 对应字段 : level
     */
    private String level;

    /**
     * 
     * 表 : t_log_detail
     * 对应字段 : thread_name
     */
    private String threadName;

    /**
     * 
     * 表 : t_log_detail
     * 对应字段 : class_name
     */
    private String className;

    /**
     * 
     * 表 : t_log_detail
     * 对应字段 : timestamp
     */
    private String timestamp;

    /**
     * 
     * 表 : t_log_detail
     * 对应字段 : body
     */
    private String body;

    /**
     * 
     * 表 : t_log_detail
     * 对应字段 : create_date
     */
    private Date createDate;

    /**
     * 
     * 表 : t_log_detail
     * 对应字段 : create_user
     */
    private String createUser;

    /**
     * 
     * 表 : t_log_detail
     * 对应字段 : update_date
     */
    private Date updateDate;

    /**
     * 
     * 表 : t_log_detail
     * 对应字段 : update_user
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_log_detail
     *
     * @mbggenerated Fri Sep 21 10:45:00 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * get method 
     *
     * @return t_log_detail.id：
     */
    public String getId() {
        return id;
    }

    /**
     * set method 
     *
     * @param id  
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * get method 
     *
     * @return t_log_detail.ip：
     */
    public String getIp() {
        return ip;
    }

    /**
     * set method 
     *
     * @param ip  
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * get method 
     *
     * @return t_log_detail.app_name：
     */
    public String getAppName() {
        return appName;
    }

    /**
     * set method 
     *
     * @param appName  
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * get method 
     *
     * @return t_log_detail.level：
     */
    public String getLevel() {
        return level;
    }

    /**
     * set method 
     *
     * @param level  
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * get method 
     *
     * @return t_log_detail.thread_name：
     */
    public String getThreadName() {
        return threadName;
    }

    /**
     * set method 
     *
     * @param threadName  
     */
    public void setThreadName(String threadName) {
        this.threadName = threadName == null ? null : threadName.trim();
    }

    /**
     * get method 
     *
     * @return t_log_detail.class_name：
     */
    public String getClassName() {
        return className;
    }

    /**
     * set method 
     *
     * @param className  
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * get method 
     *
     * @return t_log_detail.timestamp：
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * set method 
     *
     * @param timestamp  
     */
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp == null ? null : timestamp.trim();
    }

    /**
     * get method 
     *
     * @return t_log_detail.body：
     */
    public String getBody() {
        return body;
    }

    /**
     * set method 
     *
     * @param body  
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * get method 
     *
     * @return t_log_detail.create_date：
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * set method 
     *
     * @param createDate  
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * get method 
     *
     * @return t_log_detail.create_user：
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * set method 
     *
     * @param createUser  
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * get method 
     *
     * @return t_log_detail.update_date：
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * set method 
     *
     * @param updateDate  
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * get method 
     *
     * @return t_log_detail.update_user：
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * set method 
     *
     * @param updateUser  
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ip=").append(ip);
        sb.append(", appName=").append(appName);
        sb.append(", level=").append(level);
        sb.append(", threadName=").append(threadName);
        sb.append(", className=").append(className);
        sb.append(", timestamp=").append(timestamp);
        sb.append(", body=").append(body);
        sb.append(", createDate=").append(createDate);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateUser=").append(updateUser);
        sb.append("]");
        return sb.toString();
    }
}